version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - .:/app
      - backend_node_modules:/app/node_modules
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    volumes:
      - .:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development

volumes:
  backend_node_modules:
  frontend_node_modules: 